### ISSUE TITLE
fortuna.count is NaN

### ISSUE THREAD

**Issue by FrancoPinoC** [sethblack/javascript-fortuna#8]
Was poking at the properties of the fortuna object to figure some things out and fortuna.count came out as NaN. Looking at fortuna.js it seems like there was a typo where the property is originally defined as `counter` but then used as `count`(?)

**Comment by sethblack** [comment]
Wow. Good catch. Very true. Lemme fix that.

**Comment by FrancoPinoC** [comment]
Thanks for the quick response! (sorry to bother you again! but you missed line 99 ^^' )

**Comment by sethblack** [comment]
No problem. (Whoops. My bad. Fixed, again.)
